# The Travis setup:
# - run testsuite for every PHP version
# - run lint for PHP 7.1
# - run Selenium for PHP 7.1
# - deploy PMA to Google App Engine

dist: trusty

language: php

services:
  - mysql

sudo: required

env:
  global:
    - TESTSUITE_USER=root
    - TESTSUITE_URL=http://127.0.0.1:8000
    
install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then source ~/virtualenv/python3.6/bin/activate ; fi
  - ./$CI_TYPE/ci-install-$CI_MODE
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then case "$TRAVIS_PHP_VERSION" in hhvm*) ;; *) phpenv config-add test/php-noprofile.ini ;; esac ; fi

before_script:
  - export TESTSUITE_PASSWORD=`openssl rand -base64 30`
  - export TESTSUITE_BROWSERSTACK_KEY=`echo cHlDcHJTNmZwZjVlaUR2RmV6VkU= | base64 --decode`
  - export PATH=~/.composer/vendor/bin/:$PATH
  - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS test"
  - mysql -uroot < sql/create_tables.sql
  - mysql -uroot -e "SET PASSWORD = PASSWORD('$TESTSUITE_PASSWORD')"
  - ./test/start-local-server

script:
  - ./scripts/generate-mo --quiet
  - if [[ "$CI_MODE" = "test" ]] ; then ./test/ci-phplint ; fi
  - ./test/ci-$CI_MODE

after_script:
  - if [ -f vendor/bin/codacycoverage ] ; then php vendor/bin/codacycoverage clover || true ; fi
  - if [ -f php.log ] ; then cat php.log ; fi
  - if [ -f nginx-error.log ] ; then cat nginx-error.log ; fi
  - if [ -f build/logs/phpunit.json ] ; then ./scripts/phpunit-top-tests build/logs/phpunit.json ; fi
  - if [ -f config.inc.php ] ; then rm -rf config.inc.php; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

stages:
  - test
  - deploy
  - failable

jobs:
  # Jobs that must succeed for deployment to occur
  include:
    # Basic testing jobs
    - stage: test
      php: "7.2"
      env: CI_TYPE=test CI_MODE=test
    - stage: test
      php: "7.1"
      env: CI_TYPE=test CI_MODE=test
    # Other testing jobs
    - stage: test
      php: "7.1"
      env: CI_TYPE=test CI_MODE=selenium
    - stage: test
      php: "7.1"
      env: CI_TYPE=test CI_MODE=lint
    - stage: test
      php: "7.1"
      env: CI_TYPE=test CI_MODE=release
    - stage: test
      php: "7.1"
      env: CI_TYPE=test CI_MODE=docs
    - stage: test
      php: "7.1"
      env: CI_TYPE=test CI_MODE=apidocs
    - stage: test
      php: "7.2"
      os: osx
      language: generic
      env: CI_TYPE=test CI_MODE=test
      before_install:
        - brew update
        - brew install gettext php72 mariadb
        - brew link --force gettext
        - sed -i -e 's/^memory_limit = .*/memory_limit = -1/' /usr/local/etc/php/7.2/php.ini
        - curl https://getcomposer.org/installer | php
        - ln -s "`pwd`/composer.phar" /usr/local/bin/composer
        - mysql.server start
    # Deployment job
    - stage: deploy
      php: "7.2"
      env: CI_TYPE=deploy CI_MODE=deploy
      before_install:
        - ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine
        - openssl aes-256-cbc -K $encrypted_93cd6078427b_key -iv $encrypted_93cd6078427b_iv
          -in travis-gae-keyfile.json.enc -out travis-gae-keyfile.json -d
      before_script: skip
      script: skip
      deploy:
        provider: gae
        skip_cleanup: true
        keyfile: travis-gae-keyfile.json
        project: the-giganibbles-phpmyadmin
        on: 
          branch: working
    # Jobs that can fail for the build to still succeed and deployment to occur
    - stage: failable
      php: "nightly"
      env: CI_MODE=test
    - stage: failable
      php: "7.2"
      env: CI_MODE=phpstan
cache:
  pip: true
  directories:
    - $HOME/.composer/cache/
    - $HOME/browserstack
# Install APT packages
#  - git > 2.5.1 needed for worktrees
#  - mysql server does not seem to be always present on Travis Trusty environment
addons:
  apt:
    packages:
    - git
    - mysql-server-5.6
    - nginx