runtime: php
env: flex

runtime_config: 
  document_root: .
  whitelist_functions: "php_uname, getmypid"
  
beta_settings:
  cloud_sql_instances: "the-giganibbles-phpmyadmin:australia-southeast1:the-giganibbles-mysql"